point to rebuilt cvs2git
the old one broke[1], and pointed to the volatile /software/bin/python;
this is made with explicit /software/bin/python-2.7.1

[1]
Traceback (most recent call last):
  File "/nfs/users/nfs_m/mca/gitwk-ext/cvs2svn/INST.230/software/python-2.5/bin/cvs2git", line 66, in <module>
    from cvs2svn_lib.main import git_main
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/main.py", line 30, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/svn_run_options.py", line 40, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/svn_output_option.py", line 49, in <module>
  File "/software/python-2.5/lib/python2.5/site-packages/cvs2svn_lib/dumpfile_delegate.py", line 23, in <module>
  File "/software/python-2.5/lib/python2.5/md5.py", line 6, in <module>
    from hashlib import md5
  File "/software/python-2.5/lib/python2.5/hashlib.py", line 104, in <module>
    md5 = __get_builtin_constructor('md5')
  File "/software/python-2.5/lib/python2.5/hashlib.py", line 31, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5

diff --git a/cvs2git b/cvs2git
--- a/cvs2git
+++ b/cvs2git
@@ -2,13 +2,24 @@
 
 # This is a wrapper script to set the install path (I use v2.3.0) and
 # run the program there
+#
+#
+# To get my installed copy, I did something like
+#
+#   svn checkout http://cvs2svn.tigris.org/svn/cvs2svn
+#   # actually it looks like I used "git-svn clone"
+#
+#   cd cvs2svn
+#   ...get on the 2.3.0 release
+#
+#   make install DESTDIR=INST.230.271 PYTHON=/software/bin/python-2.7.1
 
-CVS2SVN_INST="$HOME/gitwk-ext/cvs2svn/INST.230/software/python-2.5"
+CVS2SVN_INST="$HOME/gitwk-ext/cvs2svn/INST.230.271/software/python-2.7.1"
 if [ ! -d $CVS2SVN_INST ]; then
-    echo -e "cvs2svn: install expected in\n  $CVS2SVN_INST\n but not found.  mca had an install of this 2010-11 to 2011-03" >&2
+    echo -e "cvs2svn: install expected in\n  $CVS2SVN_INST\n but not found.  mca had an install of this 2010-11 to 2012-02" >&2
     exit 1
 fi
 
-export PYTHONPATH="$CVS2SVN_INST/lib/python2.5/site-packages"
+export PYTHONPATH="$CVS2SVN_INST/lib/python2.7/site-packages"
 
 exec $CVS2SVN_INST/bin/cvs2git $*
