Accept CVS2SVN_INST directory from environment
Probably needs to be passed in from the crontab or whatever

diff --git a/cvs2git b/cvs2git
--- a/cvs2git
+++ b/cvs2git
@@ -14,9 +14,9 @@
 #
 #   make install DESTDIR=INST.230.271 PYTHON=/software/bin/python-2.7.1
 
-CVS2SVN_INST="$HOME/Opt/cvs2svn-2.4.0/software/python-2.7.3"
+: ${CVS2SVN_INST:="$HOME/mumble/cvs2svn-2.4.0/software/python-2.7.3"}
 if [ ! -d $CVS2SVN_INST ]; then
-    echo -e "cvs2svn: install expected in\n  $CVS2SVN_INST\n but not found.  mca had an install of this 2010-11 to 2012-02" >&2
+    echo -e "cvs2svn: install expected in\n  $CVS2SVN_INST\n but not found.\n\n Please point CVS2SVN_INST at your cvs2svn DESTDIR - it should contain bin/cvs2git ." >&2
     exit 1
 fi
 
